/**
 * Taxi Platform API
 * Backend API contract for authentication, rides, admin operations, and websocket ride updates.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Location } from './location';
import { RideStatus } from './rideStatus';


export interface ActiveRideResponse { 
    id: string;
    passengerId: string;
    passengerName: string;
    driverId?: string | null;
    driverName?: string | null;
    pickupLocation: Location;
    dropoffLocation: Location;
    status: RideStatus;
    price: number;
    distance: number;
    estimatedTime: number;
    createdAt: string;
    acceptedAt?: string | null;
    completedAt?: string | null;
}
export namespace ActiveRideResponse {
}


