/**
 * Taxi Platform API
 * Backend API contract for authentication, rides, admin operations, and websocket ride updates.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DriverRideRequestWsEventData } from './driverRideRequestWsEventData';


export interface DriverRideRequestWsEvent { 
    type: DriverRideRequestWsEvent.TypeEnum;
    data: DriverRideRequestWsEventData;
}
export namespace DriverRideRequestWsEvent {
    export type TypeEnum = 'DRIVER_RIDE_REQUEST';
    export const TypeEnum = {
        DriverRideRequest: 'DRIVER_RIDE_REQUEST' as TypeEnum
    };
}


