/**
 * Taxi Platform API
 * Backend API contract for authentication, rides, admin operations, and websocket ride updates.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DriverApplication { 
    id: string;
    userId: string;
    firstName: string;
    lastName: string;
    phone: string;
    licenseNumber: string;
    carModel: string;
    carYear: number;
    carPlate: string;
    carColor: string;
    status: DriverApplication.StatusEnum;
    createdAt: string;
}
export namespace DriverApplication {
    export type StatusEnum = 'PENDING' | 'APPROVED' | 'REJECTED';
    export const StatusEnum = {
        Pending: 'PENDING' as StatusEnum,
        Approved: 'APPROVED' as StatusEnum,
        Rejected: 'REJECTED' as StatusEnum
    };
}


