/**
 * Taxi Platform API
 * Backend API contract for authentication, rides, admin operations, and websocket ride updates.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AcceptRideWsCommandData } from './acceptRideWsCommandData';


export interface RejectRideWsCommand { 
    type: RejectRideWsCommand.TypeEnum;
    data: AcceptRideWsCommandData;
}
export namespace RejectRideWsCommand {
    export type TypeEnum = 'REJECT_RIDE';
    export const TypeEnum = {
        RejectRide: 'REJECT_RIDE' as TypeEnum
    };
}


