/**
 * Taxi Platform API
 * Backend API contract for authentication, rides, admin operations, and websocket ride updates.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Coordinates } from './coordinates';
import { RideStatus } from './rideStatus';


export interface RideUpdateWsEventData { 
    rideId: string;
    status: RideStatus;
    driverId?: string | null;
    driverName?: string | null;
    driverPhone?: string | null;
    driverLocation?: Coordinates;
    estimatedArrival?: number | null;
    message?: string | null;
}
export namespace RideUpdateWsEventData {
}


