/**
 * Taxi Platform API
 * Backend API contract for authentication, rides, admin operations, and websocket ride updates.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Location } from './location';
import { RideStatus } from './rideStatus';


export interface RideAvailable { 
    id: string;
    passengerName: string;
    pickupLocation: Location;
    dropoffLocation: Location;
    status: RideStatus;
    price: number;
    distance: number;
    estimatedTime?: number | null;
}
export namespace RideAvailable {
}


