/**
 * Taxi Platform API
 * Backend API contract for authentication, rides, admin operations, and websocket ride updates.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RideUpdateWsEventData } from './rideUpdateWsEventData';


export interface RideUpdateWsEvent { 
    type: RideUpdateWsEvent.TypeEnum;
    data: RideUpdateWsEventData;
}
export namespace RideUpdateWsEvent {
    export type TypeEnum = 'RIDE_UPDATE';
    export const TypeEnum = {
        RideUpdate: 'RIDE_UPDATE' as TypeEnum
    };
}


