/**
 * Taxi Platform API
 * Backend API contract for authentication, rides, admin operations, and websocket ride updates.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateLocationWsCommandData } from './updateLocationWsCommandData';


export interface UpdateLocationWsCommand { 
    type: UpdateLocationWsCommand.TypeEnum;
    data: UpdateLocationWsCommandData;
}
export namespace UpdateLocationWsCommand {
    export type TypeEnum = 'UPDATE_LOCATION';
    export const TypeEnum = {
        UpdateLocation: 'UPDATE_LOCATION' as TypeEnum
    };
}


