/**
 * Taxi Platform API
 * Backend API contract for authentication, rides, admin operations, and websocket ride updates.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRole } from './userRole';


export interface UserProfile { 
    id: string;
    email: string;
    name: string;
    phone?: string | null;
    roles: Array<UserRole>;
    isDriver: boolean;
    driverApproved?: boolean | null;
    profilePhoto?: string | null;
}

